# NUMPY

In [3]:
import numpy as np

In [12]:
# Create an array with the arange() function and reshape the array as follows:
# a = np.arange(24).reshape(2,3,4)
# This gives us a 3-dimensional data structure. 
# You can think of it as being like 2 spreadsheet sheets where each sheet contains 3 rows of data and each row contains 4 columns.
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
# Use the ravel() function to flatten the ndarray. 
# Investigate the difference between ravel() and flatten()

arr1 = [0,2,3,4]
arr1 = np.array ([0,2,3,4])
arr1

array([0, 2, 3, 4])

In [27]:
arr1.ravel() #ravel stays the same even when the value for the original changes

array([0, 2, 3, 4])

In [28]:
arr1.flatten() #flatten changes when the value for the original changes

array([0, 2, 3, 4])

In [32]:
# Reshape the ndarray so that there are 6 rows and 4 columns
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
# Find the transpose of the ndarray.
arr2.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [48]:
# Re-stack the rows of the transposed ndarray in reverse order.
# Hint: the documentation for row_stack() function might be of help here.
arr3 = np.row_stack(arr2[::-1])
arr3

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23],
       [ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [49]:
#  Split the resulting ndarray column-wise.
# Hint: look at the documentation for the hsplit() function.
split_arrays = np.hsplit(arr3,2)
split_arrays

[array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22],
        [ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23],
        [ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]])]

# NUMPY DATA OPERATIONS

In [50]:
# You will need two data files (available on Moodle) for this part of the tutorial, the file AAPL.csv contains stock price data for Apple. 
# The file MSFT.csv contains stock price data for Microsoft.
# 1. Use the loadtxt() function to load columns 5 and 7 (i.e., the closing price and the volume) from AAPL.csv.
# 2. Use the loaded data to calculate the volume weighted average price for the stock (i.e., cal- culate the average price using the volume as weight values).
# 3. Calculate the median value of the closing prices
# 4. Calculate the variance of the closing prices.
# 5. Use the loadtxt() function to load data from columns 3 and 4 (i.e., the high and low prices) from AAPL.csv.
# 6. Find the highest of the high prices and the lowest of the low prices.
# 7. Load data from column 5 of AAPL.csv. Also, load data from column 5 of MSFT.csv.
# 8. CalculatethecovariancematrixoftheclosingpricesofAAPLandMSFT.Assigntheresult- ing covariance matrix to a new variable.
# Hint: Use the cov() function.
# 9. Return an ndarray containing only the values on the diagonal of the covariance matrix.
# 10. Calculate the correlation coefficient of the closing prices of AAPL and MSFT.

In [4]:
import numpy as np

In [6]:
# 1. Use the loadtxt() function to load columns 5 and 7 (i.e., the closing price and the volume) from AAPL.csv.
ft = np.loadtxt('/Users/Latifa/Desktop/Semester 1/Analytics Programming/Tutorials/AAPL.csv',delimiter=',', skiprows=1, usecols=(4, 6))

In [7]:
# 2. Use the loaded data to calculate the volume weighted average price for the stock
arr1 = ft[:,0]
arr2 = ft[:,1]
weighted_average = np.sum(arr1*arr2)/np.sum(arr2)
weighted_average

190.02952578964312

In [78]:
# 3. Calculate the median value of the closing prices
median = np.median(arr1)
median

197.0

In [79]:
# 4. Calculate the variance of the closing prices.
var = np.var(arr1)
var

432.8804568188714

In [10]:
# 5. Use the loadtxt() function to load data from columns 3 and 4 (i.e., the high and low prices) from AAPL.csv.
ft = np.loadtxt('/Users/Latifa/Desktop/Semester 1/Analytics Programming/Tutorials/AAPL.csv',delimiter=',', skiprows=1, usecols=(2, 3))

In [81]:
# 6. Find the highest of the high prices and the lowest of the low prices.
arr3 = ft[:,0]
arr4 = ft[:,1]

In [82]:
highest = np.max(arr3)
highest

229.929993

In [84]:
lowest = np.min(arr4)
lowest

142.0

In [11]:
# 7. Load data from column 5 of AAPL.csv. Also, load data from column 5 of MSFT.csv.
ft = np.loadtxt('/Users/Latifa/Desktop/Semester 1/Analytics Programming/Tutorials/AAPL.csv',delimiter=',', skiprows=1, usecols=(4))
lt = np.loadtxt('/Users/Latifa/Desktop/Semester 1/Analytics Programming/Tutorials/MSFT.csv',delimiter=',', skiprows=1, usecols=(4))

In [94]:
# 8. CalculatethecovariancematrixoftheclosingpricesofAAPLandMSFT.Assigntheresulting covariance matrix to a new variable.
arr5 = ft[:]
arr6 = lt[:]

In [98]:
covariance = np.cov(arr5,arr6)
covariance

array([[434.60508015, 186.97834783],
       [186.97834783, 184.73421932]])

In [99]:
# 9. Return an ndarray containing only the values on the diagonal of the covariance matrix.
diagonal = np.diag(covariance)
diagonal

array([434.60508015, 184.73421932])

In [100]:
# 10. Calculate the correlation coefficient of the closing prices of AAPL and MSFT.
correlation = np.corrcoef(arr5,arr6)
correlation

array([[1.        , 0.65988802],
       [0.65988802, 1.        ]])